---
# file: roles/cis_rhel6/tasks/section_02_level1.yml
#
# Copyright 2014 Major Hayden
#           2017 Roger Nem
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: "Services | 2.1.1 - 2.1.5 Ensure xinetd services are not enabled (check if exists) (Scored)"
    stat:
      path: "/etc/xinetd.d/{{ item }}"
    register: found_xinetd_services
    when: xinetd_services is defined
    with_items:
      - "{{ xinetd_services }}"
    tags:
      - scored
      - section2.1
      - section2.1.1
      - section2.1.2
      - section2.1.3
      - section2.1.4
      - section2.1.5

  - name: "Services | 2.1.1 - 2.1.5 Ensure xinetd services are not enabled (disable service) (Scored)"
    service:
      name: "{{ item.item }}"
      state: stopped
      enabled: no
    with_items:
      - "{{ found_xinetd_services.results }}"
    when:
      - item.stat.exists
      - "xinetd_services != []"
    tags:
      - scored
      - section2.1
      - section2.1.1
      - section2.1.2
      - section2.1.3
      - section2.1.4
      - section2.1.5

  - name: "Services | 2.1.11 Ensure xinetd is not enabled (remove package) (Scored)"
    yum:
      name: xinetd
      state: absent
    when: "misc_packages_managed is not defined or 'xinetd' not in misc_packages_managed"
    tags:
      - scored
      - section2.1
      - section2.1.11

  - name: "Services | 2.1.6 - 2.1.9 Ensure insecure servers are not enabled (Scored)"
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ insecure_servers }}"
    when:
      - "insecure_servers is defined"
      - "insecure_servers != []"
    tags:
      - scored
      - section2.1
      - section2.1.6

  - name: "Services | 2.1.10 Ensure rsync service is not enabled (remove package) (Scored)"
    yum:
      name: rsync
      state: absent
    when: "misc_packages_managed is not defined or 'rsync' not in misc_packages_managed"
    tags:
      - scored
      - section2.1
      - section2.1.10

  - name: "Services | 2.2.1.1 - 2.2.1.2 Ensure NTP is configured (Scored)"
    include_role:
      name: common
      tasks_from: ntpd
      vars_from: RedHat6
    tags:
      - scored
      - section2.2
      - section2.2.1
      - section2.2.1.1
      - section2.2.1.2

  - name: "Services | 2.2.1.3 Ensure Chrony is configured (Scored)"
    debug:
      msg: "*** NTP is used at SPE, not Chrony."
    tags:
      - scored
      - section2.2
      - section2.2.1
      - section2.2.1.3

  - name: "Services | 2.2.2 Ensure X Window System is not installed (Scored)"
    yum:
      name: "xorg-x11-*"
      state: absent
    when: "misc_packages_managed is not defined or ('xorg-x11-server-Xvfb' not in misc_packages_managed and 'xorg-x11-xauth' not in misc_packages_managed)"
    tags:
      - scored
      - section2.2
      - section2.2.2

  - name: "Services | 2.2.3 Ensure Avahi server is not enabled (check if installed) (Scored)"
    stat:
      path: /etc/init.d/avahi-daemon
    register: avahi_service
    tags:
      - scored
      - section2.2
      - section2.2.3

  - name: "Services | 2.2.3 Ensure Avahi server is not enabled (disable service) (Scored)"
    service:
      name: avahi-daemon
      state: stopped
      enabled: no
    when: avahi_service.stat.exists
    tags:
      - scored
      - section2.2
      - section2.2.3

  - name: "Services | 2.2.4 Ensure CUPS is not enabled (check if installed) (Scored)"
    stat:
      path: /etc/init.d/cups
    register: cups_service
    tags:
      - scored
      - section2.2
      - section2.2.4

  - name: "Services | 2.2.4 Ensure CUPS is not enabled (disable print server) (Scored)"
    service:
      name: cups
      state: stopped
      enabled: no
    ignore_errors: "{{ continue_after_error }}"
    when:
      - cups_service.stat.exists
      - "misc_packages_managed is not defined or 'cups' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.4

  - name: "Services | 2.2.4 Ensure CUPS is not enabled (remove package) (Scored)"
    yum:
      name: cups
      state: absent
    when:
      - "misc_packages_managed is not defined or 'cups' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.4

  - name: "Services | 2.2.5 Ensure DHCP server is not enabled (remove package) (Scored)"
    yum:
      name: dhcp
      state: absent
    when: "misc_packages_managed is not defined or 'dhcp' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.5

  - name: "Services | 2.2.6 Ensure LDAP server is not enabled (remove package) (Scored)"
    yum:
      name: openldap-servers
      state: absent
    when: "misc_packages_managed is not defined or 'openldap-servers' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.6

  - name: "Services | 2.2.7 Ensure NFS and RPC are not enabled (check if NFS is in use on host) (Scored)"
    command: "grep nfs /etc/fstab"
    register: nfs_absent
    check_mode: no
    changed_when: no
    failed_when: no
    tags:
      - scored
      - section2.2
      - section2.2.7

  - name: "Services | 2.2.7 Ensure NFS and RPC are not enabled (check for nfs-utils) (Scored)"
    stat:
      path: /etc/init.d/nfslock
    register: nfs_utils
    # nfs_absent.rc will be "1" if "nfs" could not be found in /etc/fstab
    # if "nfs" is present in /etc/fstab, we are mounting NFS shares hence require the tools
    when: nfs_absent.rc
    tags:
      - scored
      - section2.2
      - section2.2.7

  - name: "Services | 2.2.7 Ensure NFS and RPC are not enabled (check for rpcbind) (Scored)"
    stat:
      path: /etc/init.d/rpcbind
    register: rpcbind
    when: nfs_absent.rc
    tags:
      - scored
      - section2.2
      - section2.2.7

  - name: "Services | 2.2.7 Ensure NFS and RPC are not enabled (disable misc services) (Scored)"
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - nfslock
      - rpcgssd
      - rpcidmapd
      - rpcsvcgssd
    ignore_errors: "{{ continue_after_error }}"
    when:
      - nfs_utils.stat.exists
      - nfs_absent.rc
    tags:
      - scored
      - section2.2
      - section2.2.7

  - name: "Services | 2.2.7 Ensure NFS and RPC are not enabled (disable rpcbind) (Scored)"
    service:
      name: rpcbind
      state: stopped
      enabled: no
    when:
      - rpcbind.stat.exists
      - nfs_absent.rc
    tags:
      - scored
      - section2.2
      - section2.2.7

  - name: "Services | 2.2.8 Ensure DNS server is not enabled (remove package) (Scored)"
    yum:
      name: bind
      state: absent
    when: "misc_packages_managed is not defined or 'bind' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.8

  - name: "Services | 2.2.9 Ensure FTP server is not enabled (remove package) (Scored)"
    yum:
      name: vsftpd
      state: absent
    when: "misc_packages_managed is not defined or 'vsftpd' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.9

  - name: "Services | 2.2.10 Ensure HTTP server is not enabled (remove package) (Scored)"
    yum:
      name: httpd
      state: absent
    when:
      - "apache_managed is undefined or apache_managed == false"
      - "misc_packages_managed is not defined or 'httpd' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.10

  - name: "Services | 2.2.11 Ensure IMAP and POP3 server is not enabled (remove package) (Scored)"
    yum:
      name: dovecot
      state: absent
    when: "misc_packages_managed is not defined or 'dovecot' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.11

  - name: "Services | 2.2.12 Ensure Samba is not enabled (remove package) (Scored)"
    yum:
      name: samba
      state: absent
    when: "samba is not defined or samba.shares.name is not defined"
    tags:
      - scored
      - section2.2
      - section2.2.12

  - name: "Services | 2.2.13 Ensure HTTP proxy server is not enabled (remove package) (Scored)"
    yum:
      name: squid
      state: absent
    when: "misc_packages_managed is not defined or 'squid' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.13

  - name: "Services | 2.2.14 Ensure SNMP server is not enabled (remove package) (Scored)"
    yum:
      name: net-snmp
      state: absent
    when: "misc_packages_managed is not defined or 'net-snmp' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.14

  - name: "Services | 2.2.15 Ensure mail transfer agent is configured for local-only mode (verify SMTP server is installed) (Scored)"
    yum:
      name: postfix
      state: present
    tags:
      - scored
      - section2.2
      - section2.2.15

  - name: "Services | 2.2.15 Ensure mail transfer agent is configured for local-only mode (enforce local-only mode) (Scored)"
    lineinfile:
      backup: yes
      state: present
      dest: /etc/postfix/main.cf
      backrefs: yes
      regexp: "^.*inet_interfaces"
      line: "inet_interfaces = localhost"
    ignore_errors: "{{ continue_after_error }}"
    tags:
      - scored
      - section2.2
      - section2.2.15

  - name: "Services | 2.2.16 Ensure NIS server is not enabled (remove package) (Scored)"
    yum:
      name: ypserv
      state: absent
    when: "misc_packages_managed is not defined or 'ypserv' not in misc_packages_managed"
    tags:
      - scored
      - section2.2
      - section2.2.16

  - name: "Services | 2.3.1 Ensure NIS client is not installed (remove package) (Scored)"
    yum:
      name: ypbind
      state: absent
    when: "misc_packages_managed is not defined or 'ypbind' not in misc_packages_managed"
    tags:
      - scored
      - section2.3
      - section2.3.1

  - name: "Services | 2.3.2 Ensure insecure clients are not installed (remove packages) (Scored)"
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ insecure_clients }}"
    when:
      - "insecure_clients is defined"
      - "insecure_clients != []"
    tags:
      - scored
      - section2.3
      - section2.3.2

  - name: "Services | 2.3.5 Ensure LDAP client is not installed (remove package) (Scored)"
    yum:
      name: openldap-clients
      state: absent
    when: "misc_packages_managed is not defined or 'openldap-clients' not in misc_packages_managed"
    tags:
      - scored
      - section2.3
      - section2.3.5

...
# vim:ft=ansible: