---
# defaults file for roles/subscribe_satellite

## Local Repo File
dvdrepo_manage: false

## Satellite defaults
satellite_manage: true
satellite_debug: false

satellite_host: livesathost.domain.com
satellite_prior_host: oldsathost.domain.com

satellite_package_name: katello-ca-consumer-{{ satellite_host }}.noarch
satellite_prior_package_name: katello-ca-consumer-{{ satellite_prior_host }}.noarch

satellite_rpm_url: "https://{{ satellite_host }}/pub/katello-ca-consumer-latest.noarch.rpm"
satellite_org: COMPANY_ORG

#Activation-Key Scheme for COMPANY_ORG Satellite Organization - 
# Primary-keys with auto-attach:
#  primary-ak_[HARDWARE VENDOR]_[OS]_[OS VERSION]_[CPU ARCH]_[SATELLITE LIFECYCLE ENVIRONMENT]_[SATELLITE CONTENT VIEW IN LIFECYCLE ENVIRONMENT]
# Extra Activation Keys do not have auto-attach and only enable specfied products:
#  extra-ak_[PRODUCT NAME]

#Activation keys listed in satellite_activation_keys list will be sorted alphabetically
# because the former listed keys' settings will override former listed keys
# A to the E(extra-ak*) to the P(primary-ak*) to the Z

satellite_hardware_vendor: "{{ ansible_system_vendor.split(' ') | first | replace(',', '') | upper }}"
satellite_hardware_type: "{{ satellite_hardware_vendor }}-{{ satellite_hardware_model }}"
satellite_CV: ccv-team-standard
satellite_primary_activation_key: primary-ak_{{ satellite_hardware_vendor }}_RHEL_{{ ansible_distribution_major_version }}Server_x86_{{ satellite_LCE }}_{{ satellite_CV }}
satellite_activation_keys:
 - "{{ satellite_primary_activation_key }}"


#Below are just list of repo to be used in the satellite_activation_key_repos dictionary
# It is so that only one place has to be updated for standard repos are defined for the
# standard activation-keys.

satellite_standard_HP_RHEL6Server_repos:
- rhel-6-server-optional-rpms
- rhel-6-server-satellite-tools-6.1-rpms
- rhel-6-server-rpms
- rhel-6-server-thirdparty-oracle-java-rpms
- COMPANY_ORG_Fedora_EPEL_EPEL6_x86_64

satellite_standard_HP_RHEL7Server_repos:
- rhel-7-server-optional-rpms
- rhel-7-server-satellite-tools-6.1-rpms
- rhel-7-server-rpms
- rhel-7-server-extras-rpms
- rhel-7-server-thirdparty-oracle-java-rpms
- COMPANY_ORG_Fedora_EPEL_EPEL7_x86_64

satellite_standard_DELL_RHEL6Server_repos: "{{ satellite_standard_HP_RHEL6Server_repos }}"
satellite_standard_CISCO_RHEL6Server_repos: "{{ satellite_standard_HP_RHEL6Server_repos }}"
satellite_standard_CISCO_RHEL7Server_repos: "{{ satellite_standard_HP_RHEL7Server_repos }}"
satellite_standard_LENOVO_RHEL6Server_repos: "{{ satellite_standard_HP_RHEL6Server_repos }}"
satellite_standard_LENOVO_RHEL7Server_repos: "{{ satellite_standard_HP_RHEL7Server_repos }}"

satellite_standard_VMWARE_RHEL6Server_repos:
- rhel-6-server-optional-rpms
- rhel-6-server-satellite-tools-6.1-rpms
- rhel-6-server-rpms
- rhel-6-server-thirdparty-oracle-java-rpms
- COMPANY_ORG_Fedora_EPEL_EPEL6_x86_64
- COMPANY_ORG_VMware_VMware_Tools_Latest_RHEL6_x86_64

satellite_standard_VMWARE_RHEL7Server_repos:
- rhel-7-server-optional-rpms
- rhel-7-server-satellite-tools-6.1-rpms
- rhel-7-server-rpms
- rhel-7-server-extras-rpms
- rhel-7-server-thirdparty-oracle-java-rpms
- COMPANY_ORG_Fedora_EPEL_EPEL7_x86_64

satellite_eus_LENOVO_RHEL7point2_repos:
- rhel-7-server-eus-optional-rpms
- rhel-sap-hana-for-rhel-7-server-eus-rpms
- rhel-7-server-eus-rpms
- rhel-7-server-eus-rh-common-rpms
- rhel-7-server-eus-satellite-tools-6.1-rpms
- rhel-7-server-eus-supplementary-rpms

#There are many activation keys defined to make automation easier to register severs
# but still have them is their desired 
satellite_activation_key_repos:
  extra-ak_rhscl:
    activation_key: extra-ak_rhscl
    repositories_enabled:
      - rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms
  extra-ak_jenkins:
    activation_key: extra-ak_jenkins
    repositories_enabled:
      - COMPANY_ORG_Jenkins_CI_Jenkins_CI_-_Latest
  extra-ak_sap-hana:
    activation_key: extra-ak_sap-hana
    repositories_enabled:
      - rhel-sap-hana-for-rhel-{{ ansible_distribution_major_version }}-server-rpms
  extra-ak_openshift:
    activation_key: extra-ak_openshift
    repositories_enabled:
      - rhel-7-server-ose-3.5-rpms
      - rhel-7-fast-datapath-rpms
  extra-ak_signal-sciences:
    activation_key: extra-ak_signal-sciences
    repositories_enabled:
      - COMPANY_ORG_Signal_Sciences_Corp_sigsci_release_EL{{ ansible_distribution_major_version }}_x86_64
    repositories_gpgcheck: false
  extra_ak_mongodb_enterprise_7Server:
    activation_key: extra_ak_mongodb_enterprise_7Server
    repositories_enabled:
      - COMPANY_ORG_MongoDB_MongoDB_Enterprise_3_6_EL{{ ansible_distribution_major_version }}
  extra_ak_enterprisedb_postgres_7Server:
    activation_key: extra_ak_enterprisedb_postgres_7Server
    repositories_enabled:
      - COMPANY_ORG_EnterpriseDB_Postgres_EnterpriseDB_AS10_EL{{ ansible_distribution_major_version }}_x86_64
      - COMPANY_ORG_EnterpriseDB_Postgres_EnterpriseDB_Tools_EL{{ ansible_distribution_major_version }}_x86_64
      - COMPANY_ORG_EnterpriseDB_Postgres_EnterpriseDB_Dependencies_EL{{ ansible_distribution_major_version }}_x86_64

  primary-ak_VMWARE_RHEL_7Server_x86_SAT-Infrastructure_ccv-team-satellite:
    activation_key: primary-ak_VMWARE_RHEL_7Server_x86_SOE-Production_ccv-team-satellite
    repositories_enabled:
      - rhel-7-server-rpms
      - rhel-7-server-satellite-6.1-rpms
      - rhel-7-server-satellite-tools-6.1-rpms
      - rhel-server-rhscl-7-rpms

  primary-ak_CISCO_RHEL_6Server_x86_SOE-NonProduction_ccv-team-standard:
      activation_key: primary-ak_CISCO_RHEL_6Server_x86_SOE-NonProduction_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_CISCO_RHEL6Server_repos }}"
  primary-ak_CISCO_RHEL_6Server_x86_SOE-Production_ccv-team-standard:
      activation_key: primary-ak_CISCO_RHEL_6Server_x86_SOE-Production_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_CISCO_RHEL6Server_repos }}"

  primary-ak_HP_RHEL_6Server_x86_SOE-NonProduction_ccv-team-standard:
      activation_key: primary-ak_HP_RHEL_6Server_x86_SOE-NonProduction_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_HP_RHEL6Server_repos }}"
  primary-ak_HP_RHEL_6Server_x86_SOE-Production_ccv-team-standard:
      activation_key: primary-ak_HP_RHEL_6Server_x86_SOE-Production_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_HP_RHEL6Server_repos }}"
  primary-ak_HP_RHEL_7Server_x86_SOE-NonProduction_ccv-team-standard:
      activation_key: primary-ak_HP_RHEL_7Server_x86_SOE-NonProduction_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_HP_RHEL7Server_repos }}"
  primary-ak_HP_RHEL_7Server_x86_SOE-Production_ccv-team-standard:
      activation_key: primary-ak_HP_RHEL_7Server_x86_SOE-Production_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_HP_RHEL7Server_repos }}"

  primary-ak_VMWARE_RHEL_6Server_x86_SOE-NonProduction_ccv-team-standard:
      activation_key: primary-ak_VMWARE_RHEL_6Server_x86_SOE-NonProduction_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_VMWARE_RHEL6Server_repos }}"
  primary-ak_VMWARE_RHEL_6Server_x86_SOE-Production_ccv-team-standard:
      activation_key: primary-ak_VMWARE_RHEL_6Server_x86_SOE-Production_ccv-team-standard
      repositories_enabled: "{{ satellite_standard_VMWARE_RHEL6Server_repos }}"
  primary-ak_VMWARE_RHEL_7Server_x86_SOE-NonProduction_ccv-gts-standard:
      activation_key: primary-ak_VMWARE_RHEL_7Server_x86_SOE-NonProduction_ccv-gts-standard
      repositories_enabled: "{{ satellite_standard_VMWARE_RHEL7Server_repos }}"
  primary-ak_VMWARE_RHEL_7Server_x86_SOE-Production_ccv-gts-standard:
      activation_key: primary-ak_VMWARE_RHEL_7Server_x86_SOE-Production_ccv-gts-standard
      repositories_enabled: "{{ satellite_standard_VMWARE_RHEL7Server_repos }}"

  primary-ak_LENOVO_RHEL_7point2_x86_HANA-NonProduction_ccv-gts-eus:
      activation_key: primary-ak_LENOVO_RHEL_7point2_x86_HANA-NonProduction_ccv-gts-eus
      repositories_enabled: "{{ satellite_eus_LENOVO_RHEL7point2_repos }}"
  primary-ak_LENOVO_RHEL_7point2_x86_HANA-Production_ccv-gts-eus:
      activation_key: primary-ak_LENOVO_RHEL_7point2_x86_HANA-Production_ccv-gts-eus
      repositories_enabled: "{{ satellite_eus_LENOVO_RHEL7point2_repos }}"

...
# vim:ft=ansible: