---

  - name: ssh packages
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
      - openssh-server
      - openssh-clients
      - openssh

  - name: ssh configure
    notify:
      - reload ssh
    template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
      seuser: system_u
      serole: object_r
      setype: etc_t
      backup: yes

  - name: ssh service
    service:
      name: sshd
      enabled: yes
      state: started

...
# vim:ft=ansible: