---
# file: roles/enterprisedb/tasks/edb_uninstall.yml

- name: "check if EDB service exists"
  stat:
    path: "/etc/init.d/{{ enterprisedb_service }}"
  register: service_status

- name: "stop EDB services"
  service:
    name: "{{ enterprisedb_service }}"
    state: stopped
    enabled: no
  when: service_status.stat.exists

- name: "uninstall EDB packages"
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ enterprisedb_packages }}"

- name: "remove the data folders"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ enterprisedb_path }}"
    - "/usr/share/edb"
    - "/usr/edb"
    - "/var/log/edb"
    - "/run/edb"
    - "/run/lock/edb"
    - "/etc/sysconfig/edb"
    - "/etc/edb"
  when: enterprisedb_remove_data

...
# vim:ft=ansible: