---

- name: set password to onboarding value
  hosts: all

  vars_prompt:
    - name: ticket_number
      prompt: "Please enter ticket number"
      private: no
    - name: user_account
      prompt: "Please enter user account name"
      private: no

  tasks:
  - include_vars: ../group_vars/all/user_list

  - fail:
      msg: 'cyberark status for account undefined'
    when:
      - (user_list[user_account].cyberark) is not defined

  - name: Change passwords for onboarding
    user:
      name: {{ user_account }}
      password: "****HASH*****"

  - name: set min password age for account
    command: "chage -m 0 {{ user_account }}"

  - name: Email onboarding information 
    become: no
    local_action: shell
                  echo -e "The password for {{ user_account }} on {{ inventory_hostname }} has been set.\n
                  Please onboard {{ user_account }} on this server using the predefined onboarding password pursuant to ticket {{ ticket_number }}.\n\n
                  Please work with requester of {{ ticket_number }} for any additional information needed." |
                  mailx -s "CyberArk onboard of app account {{ user_account }} on {{ inventory_hostname }} for {{ ticket_number }}." 'cyberark_team@email.com'

...
# vim:ft=ansible: